config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :products do
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:index, :create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get :search
      get :detail_search
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      post 'image_destroy', defaults: { format: 'json' }
    end
  end

  resources :signup, except: [:index, :show] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      post 'create',to:'signup#create'
      get 'done'
    end
  end
  resources :users, only: [:edit, :show, :update] do
    member do
      get :bought_products
      get :sold_products
    end
    get '/:name', controller: 'users', action: 'edit'
  end
  resources :purchase, only: [:show] do
    collection do
      post 'pay/:id', to: 'purchase#pay'
      get 'done/:id', to: 'purchase#done'
      get 'update/:id', to: 'purchase#update'
    end
  end

  resources :cards, only: [:new, :show] do
    member do
      post :pay
      post :delete
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  mount_uploader :profile_image, ImageUploader
  
  has_many :products,    dependent: :destroy

  has_many :messages, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_products, through: :likes, source: :product

  def already_liked?(product)
    self.likes.exists?(product_id: product.id)
  end

  has_many :buyed_products, foreign_key: "buyer_id", class_name: "Product"
  has_many :saling_products, -> { where("buyer_id is NULL") }, foreign_key: "saler_id", class_name: "Product"
  has_many :sold_products, -> { where("buyer_id is not NULL") }, foreign_key: "saler_id", class_name: "Product"

  has_one :cards, class_name: 'Card'

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,                         presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, on: :save_step1_to_session
  validates :nickname,                      presence: true, length: {maximum: 20}, on: :save_step1_to_session
  validates :password,                      presence: true, length: {minimum: 6, maximum: 128}, on: :save_step1_to_session
  validates :fullname_kanji,                presence: true, format: {with: /\A[ぁ-んァ-ン一-龥]/}, on: :save_step1_to_session
  validates :fullname_kana,                 presence: true, format: {with: /\A[ぁ-んァ-ヶー－]+\z/}, on: :save_step1_to_session
  validates :birthday,                      presence: true, on: :save_step1_to_session
  validates :current_address_postal_code,   presence: true, format: {with: /\A\d{7}\z/},           on: :save_step2_to_session
  validates :current_address_prefectures,   presence: true, on: :save_step2_to_session
  validates :current_address_city,          presence: true, on: :save_step2_to_session
  validates :current_address,               presence: true, on: :save_step2_to_session
  validates :current_address_building,      presence: true, on: :save_step2_to_session
  validates :tel_number,                    presence: true, format: {with: /\A\d{10,11}\z/}, on: :save_step2_to_session
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: [:edit]
  before_action :like_users, only: [:show, :bought_products, :sold_products]
  

  def show
    @saling_products = User.find(params[:id]).saling_products

  end

  def bought_products
    @bought_products = User.find(params[:id]).buyed_products
  end

  def sold_products
    @sold_products = User.find(params[:id]).sold_products
  end

  def edit
    @user = User.find(params[:user_id])
    render "users/#{params[:name]}", locals: {user: current_user}
  end

  def update
    if current_user.update(user_params)
      redirect_back(fallback_location: root_path, notice: "更新が完了しました")
    else
      render :edit
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def like_users
    @liked_users = @user.liked_products.pluck(:saler_id).uniq
  end

  def user_params
    params.require(:user).permit(
    :email,
    :nickname,
    :fullname_kanji,
    :fullname_kana,
    :birthday,
    :tel_number,
    :profile_text,
    :profile_image,
    :current_address_postal_code,
    :current_address_prefectures,
    :current_address_city,
    :current_address_,
    :current_address_building,
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_sidebar.html.haml
= link_to({controller: "users", action: "edit", name: "edit"}, class: "text-decoration-none font-color-black") do
  .user-edit-container__sidebar__item
    基本情報
= link_to({controller: "users", action: "edit", name: "delivery_address"}, class: "text-decoration-none font-color-black") do
  .user-edit-container__sidebar__item
    届け先住所

app/views/users/_mypage_middle.html.haml
.my-page__user-prof__detail
  .my-page__user-prof__detail__image
    - if @user.profile_image.blank?
      = image_tag "https://demo.a-blogcms.jp/media/001/201902/1c35033abff55e4664a216314d599201.png", class: "profile-image"
    - else
      = image_tag @user.profile_image.to_s, class: "profile-image"
  .my-page__user-prof__detail__text
    .my-page__user-prof__detail__text__box
      .my-page__user-prof__detail__text__box__users-info
        ユーザー名：
        = user.nickname
        - if current_user.id == @user.id
          = link_to edit_user_path(current_user) , class: "users-info-edit" do
            = fa_icon "cogs", class: "user-cogs"
        
      .my-page__user-prof__detail__text__box__users-status
        .my-page__user-prof__detail__text__box__users-status__posts-count
          投稿数：#{@user.saling_products.count}件
        .my-page__user-prof__detail__text__box__users-status__liked-posts
          お気に入り記事数：#{@user.liked_products.count}件
        .my-page__user-prof__detail__text__box__users-status__liked-users
          お気に入りユーザー数：#{@liked_users.reject{|n| n == current_user.id}.count}件
      .my-page__user-prof__detail__text__box__profile-text
        = user.profile_text

app/views/users/_myproducts.html.haml
- if products.present?
  - products.each do |product|
    = link_to product_path(product.id) ,class: "my-page__users-posts__post__show" do
      = image_tag product.images[0].image.url , class: "users-post-image"

- else
  まだ該当する商品はありません。

app/views/users/bought_products.html.haml
= render partial: "shared/sub_header"
.my-page
  .my-page__user-prof
    = render "mypage_middle", user: @user
    .my-page__users-posts
      .my-page__users-posts__item
        = link_to user_path, class: "text-decoration-none font-color-light-gray" do
          .my-page__users-posts__item__status
            出品中
        = link_to sold_products_user_path, class: "text-decoration-none font-color-light-gray" do
          .my-page__users-posts__item__status
            売却済
        = link_to bought_products_user_path, class: "text-decoration-none font-color-light-gray active" do
          .my-page__users-posts__item__status
            購入済
      .my-page__users-posts__post
        = render "myproducts", products: @bought_products

app/views/users/delivery_address.html.haml
= render "shared/sub_header"
.user-edit-container
  .user-edit-container__sidebar
    = render "edit_sidebar"
  .user-edit-container__edit-info
    .user-edit-container__edit-info__title
      %h2 届け先住所
    = form_with model: @user, local: true do |f|
      .user-edit-container__edit-info__items
        .user-edit-container__edit-info__items__item
          .user-edit-container__edit-info__items__item__box
            .user-edit-container__edit-info__items__item__box__field
              %span 郵便番号
              = f.text_field :current_address_postal_code, class: "input-box"
            .user-edit-container__edit-info__items__item__box__field
              .user-edit-container__edit-info__items__item__box__field__prefecture
                %span 都道府県
              = f.select :current_address_prefectures,[["---",""],["北海道","北海道"],["青森県","青森県"],["岩手県","岩手県"],["宮城県","宮城県"],["秋田県","秋田県"],["山形県","山形県"],["福島県","福島県"],["茨城県","茨城県"],["栃木県","栃木県"],["群馬県","群馬県"],["埼玉県","埼玉県"],["千葉県","千葉県"],["東京都","東京都"],["神奈川県","神奈川県"],["新潟県","新潟県"],["富山県","富山県"],["石川県","石川県"],["福井県","福井県"],["山梨県","山梨県"],["長野県","長野県"],["岐阜県","岐阜県"],["静岡県","静岡県"],["愛知県","愛知県"],["三重県","三重県"],["滋賀県","滋賀県"],["京都府","京都府"],["大阪府","大阪府"],["兵庫県","兵庫県"],["奈良県","奈良県"],["和歌山県","和歌山県"],["鳥取県","鳥取県"],["島根県","島根県"],["岡山県","岡山県"],["広島県","広島県"],["山口県","山口県"],["徳島県","徳島県"],["香川県","香川県"],["愛媛県","愛媛県"],["高知県","高知県"],["福岡県","福岡県"],["佐賀県","佐賀県"],["長崎県","長崎県"],["熊本県","熊本県"],["大分県","大分県"],["宮崎県","宮崎県"],["鹿児島県","鹿児島県"],["沖縄県","沖縄県"]], class: "user-edit-container__edit-info__items__item__box__field__select-box"
            .user-edit-container__edit-info__items__item__box__field
              %span 市町村
              = f.text_field :current_address_city, class: "input-box"
            .user-edit-container__edit-info__items__item__box__field
              %span 番地
              = f.text_field :current_address, class: "input-box"
            .user-edit-container__edit-info__items__item__box__field
              %span 建物名
              = f.text_field :current_address_building, class: "input-box"
      .user-edit-container__edit-info__items
        = f.submit  class: "btn-default"

app/views/users/edit.html.haml
= render "shared/sub_header"
.user-edit-container
  .user-edit-container__sidebar
    = render "edit_sidebar"
  .user-edit-container__edit-info
    .user-edit-container__edit-info__title
      %h2 基本情報
    = form_with model: @user, local: true do |f|
      .user-edit-container__edit-info__items
        .user-edit-container__edit-info__items__item-left
          .user-edit-container__edit-info__items__item-left__info
            = f.label :profile_image, class: "user-edit-container__edit-info__items__item-left__info__label", title: "クリックして画像を変更" do
              - if @user.profile_image.blank?
                = image_tag "https://demo.a-blogcms.jp/media/001/201902/1c35033abff55e4664a216314d599201.png", class: "user-edit-container__edit-info__items__item-left__info__label__image", id: "img_prev", onClick:"$('#user_img').click()"
              - else
                = image_tag @user.profile_image.to_s, class: "user-edit-container__edit-info__items__item-left__info__label__image", id: "img_prev", onClick:"$('#user_img').click()"
              = f.file_field :profile_image, class: "user-edit-container__edit-info__items__item-left__info__label__file",id: "user_img"
        .user-edit-container__edit-info__items__item
          .user-edit-container__edit-info__items__item__box
            .user-edit-container__edit-info__items__item__box__field
              %span ニックネーム
              = f.text_field :nickname, class: "input-box"
            .user-edit-container__edit-info__items__item__box__field
              %span 名前（漢字）
              = f.text_field :fullname_kanji, class: "input-box"
            .user-edit-container__edit-info__items__item__box__field
              %span 名前（カナ）
              = f.text_field :fullname_kana, class: "input-box"
            .user-edit-container__edit-info__items__item__box__field
              .user-edit-container__edit-info__items__item__box__field__birthday
                %span 誕生日
              != sprintf(f.date_select(:birthday, prefix:'birthday',  prompt:"--", use_month_numbers:true, with_css_classes: true, start_year:2019, end_year:1900, date_separator:'%s'),'年','月')+'日'
            .user-edit-container__edit-info__items__item__box__field
              %span 電話番号
              = f.text_field :tel_number, class: "input-box"
      .user-edit-container__edit-info__items
        .user-edit-container__edit-info__input-area
          %span 自己紹介
          = f.text_area :profile_text, maxlength: 100 , id: "textarea", placeholder: 'コメント入力（100文字まで）'
      .user-edit-container__edit-info__items
        = f.submit  class: "btn-default"

app/views/users/show.html.haml
= render partial: "shared/sub_header"
.my-page
  .my-page__user-prof
    = render "mypage_middle", user: @user
    .my-page__users-posts
      .my-page__users-posts__item
        = link_to user_path, class: "text-decoration-none font-color-light-gray active" do
          .my-page__users-posts__item__status
            出品中
        = link_to sold_products_user_path, class: "text-decoration-none font-color-light-gray" do
          .my-page__users-posts__item__status
            売却済
        = link_to bought_products_user_path, class: "text-decoration-none font-color-light-gray" do
          .my-page__users-posts__item__status
            購入済
      .my-page__users-posts__post
        = render "myproducts", products: @saling_products

app/views/users/sold_products.html.haml
= render partial: "shared/sub_header"
.my-page
  .my-page__user-prof
    = render "mypage_middle", user: @user
    .my-page__users-posts
      .my-page__users-posts__item
        = link_to user_path, class: "text-decoration-none font-color-light-gray" do
          .my-page__users-posts__item__status
            出品中
        = link_to sold_products_user_path, class: "text-decoration-none font-color-light-gray active" do
          .my-page__users-posts__item__status
            売却済
        = link_to bought_products_user_path, class: "text-decoration-none font-color-light-gray" do
          .my-page__users-posts__item__status
            購入済
      .my-page__users-posts__post
        = render "myproducts", products: @sold_products