config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :products do
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:index, :create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get :search
      get :detail_search
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      post 'image_destroy', defaults: { format: 'json' }
    end
  end

  resources :signup, except: [:index, :show] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      post 'create',to:'signup#create'
      get 'done'
    end
  end
  resources :users, only: [:edit, :show, :update] do
    member do
      get :bought_products
      get :sold_products
    end
    get '/:name', controller: 'users', action: 'edit'
  end
  resources :purchase, only: [:show] do
    collection do
      post 'pay/:id', to: 'purchase#pay'
      get 'done/:id', to: 'purchase#done'
      get 'update/:id', to: 'purchase#update'
    end
  end

  resources :cards, only: [:new, :show] do
    member do
      post :pay
      post :delete
    end
  end
end

app/views/shared/_header.html.haml
.header
  .header__upper-box
    .header__upper-box__session-menu
      - if user_signed_in?
        = link_to user_path(current_user), class: "header__upper-box__session-menu__link" do
          .header__upper-box__session-menu__link__button
            %span My page
        = link_to destroy_user_session_path(current_user), method: :delete, class: "header__upper-box__session-menu__link" do
          .header__upper-box__session-menu__link__button
            %span Log out
      - else
        = link_to new_user_registration_path, class: "header__upper-box__session-menu__link" do
          .header__upper-box__session-menu__link__button
            %span Sign up
        = link_to new_user_session_path, class: "header__upper-box__session-menu__link" do
          .header__upper-box__session-menu__link__button
            %span Log in
  .header__top-image
    = link_to root_path, class: "" do
      %li= image_tag "livres_small.png", class: "top-image-url"
    %li - 本とともに「学び（価値）」を次へ -
  .header__bottom-box
    .header__bottom-box__top-menu
      .header__bottom-box__top-menu__button
        = form_with url: search_products_path, method: :get, local: true, class: "search-form" do |f|
          = f.text_field :keyword, type: "text", placeholder: "フリーワード検索", class: "search-form__input-box"
          %button.search-form__btn{type: "submit"}
            = fa_icon "search"
      .header__bottom-box__top-menu__button
        = link_to new_product_path, class: "text-decoration-none font-color-black" do
          %span New

app/views/shared/_sub_header.html.haml
.sub_header
  .sub_header__left-container
    = link_to root_path, class: "" do
      = image_tag "livres_small.png", class: "sub-header-logo"
  .sub_header__right-container
    - if user_signed_in?
      = link_to search_products_path, class: "text-decoration-none font-color-black" do
        .sub_header__right-container__button
          %span Search
      = link_to new_product_path, class: "text-decoration-none font-color-black" do
        .sub_header__right-container__button
          %span New
      = link_to user_path(current_user), class: "text-decoration-none font-color-black" do
        .sub_header__right-container__button
          %span My page
      = link_to destroy_user_session_path(current_user), method: :delete, class: "text-decoration-none font-color-black" do
        .sub_header__right-container__button
          %span Log out
    - else
      = link_to new_user_registration_path, class: "text-decoration-none font-color-black" do
        .sub_header__right-container__button
          %span Sign up
      = link_to new_user_session_path, class: "text-decoration-none font-color-black" do
        .sub_header__right-container__button
          %span Log in