config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :products do
    resources :likes, only: [:create, :destroy]
    resources :messages, only: [:index, :create, :destroy]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get :search
      get :detail_search
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      post 'image_destroy', defaults: { format: 'json' }
    end
  end

  resources :signup, except: [:index, :show] do
    collection do
      get 'step1'
      get 'step2'
      get 'step3'
      post 'create',to:'signup#create'
      get 'done'
    end
  end
  resources :users, only: [:edit, :show, :update] do
    member do
      get :bought_products
      get :sold_products
    end
    get '/:name', controller: 'users', action: 'edit'
  end
  resources :purchase, only: [:show] do
    collection do
      post 'pay/:id', to: 'purchase#pay'
      get 'done/:id', to: 'purchase#done'
      get 'update/:id', to: 'purchase#update'
    end
  end

  resources :cards, only: [:new, :show] do
    member do
      post :pay
      post :delete
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user, optional: true
  
  belongs_to :saler, class_name: "User", optional: true
  belongs_to :buyer, class_name: "User", optional: true

  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  has_many :messages, dependent: :destroy

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  validates :images, presence: true
  serialize :categories, JSON
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :detail_search, :get_category_children, :get_category_grandchildren]
  before_action :set_product, only: [:update, :destroy, :show, :edit] 
  before_action :load_mydata, only: [:my_product_show, :destroy, :show, :edit]
  before_action :set_like, only: [:index, :show, :search]
  
  def index
    @products = Product.where(buyer_id:nil).includes(:images).order("id DESC")
  end

  def new
    @product = Product.new
    10.times {@product.images.build}
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else 
      render :new, notice: '保存できませんでした'
    end
  end

  def show
  end

  def edit
    10.times {@product.images.build}
    @images = Image.where(product_id: @product)
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def destroy
    @products = current_user.products
    if @product.saler_id == current_user.id
      @product.destroy
      redirect_to user_path(current_user)
    else
      render :show, notice: '削除できませんでした'
    end
  end
  
  def update
    if @product.update(product_params)
      redirect_to product_path
    else
      render 'show'
    end
  end

  def search
    @products = Product.where('title LIKE(?) OR text LIKE(?)', "%#{params[:keyword]}%","%#{params[:keyword]}%").order(created_at:"desc")
    
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def detail_search
    if params[:price_min].present? && params[:price_max].present?
      search_products = Product.where('title LIKE(?) OR text LIKE(?)', "%#{params[:keyword]}%","%#{params[:keyword]}%").where('price >= ? AND price < ?',"#{params[:price_min]}","#{params[:price_max]}").order(created_at:"desc")

      search_result = []
      if params[:product][:categories][0] == false || params[:product][:categories][0] == "---"
        @products = search_products
      else
        if params[:product][:categories][1] == false || params[:product][:categories][1] == "---"
          search_products.each do |p|
            if p.categories.include?(params[:product][:categories][0])
              search_result << p
              @products = search_result
            else
              @products = []
            end
          end
        else
          if params[:product][:categories][2] == false || params[:product][:categories][2] == "---"
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][1])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          else
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][2])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          end
        end
      end
    elsif params[:price_min].present?
      search_products = Product.where('title LIKE(?) OR text LIKE(?)', "%#{params[:keyword]}%","%#{params[:keyword]}%").where('price > ?',"#{params[:price_min]}").order(created_at:"desc")

      search_result = []
      if params[:product][:categories][0] == false || params[:product][:categories][0] == "---"
        @products = search_products
      else
        if params[:product][:categories][1] == false || params[:product][:categories][1] == "---"
          search_products.each do |p|
            if p.categories.include?(params[:product][:categories][0])
              search_result << p
              @products = search_result
            else
              @products = []
            end
          end
        else
          if params[:product][:categories][2] == false || params[:product][:categories][2] == "---"
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][1])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          else
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][2])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          end
        end
      end
    elsif params[:price_max].present?
      search_products = Product.where('title LIKE(?) OR text LIKE(?)', "%#{params[:keyword]}%","%#{params[:keyword]}%").where('price < ?',"#{params[:price_max]}").order(created_at:"desc")

      search_result = []
      if params[:product][:categories][0] == false || params[:product][:categories][0] == "---"
        @products = search_products
      else
        if params[:product][:categories][1] == false || params[:product][:categories][1] == "---"
          search_products.each do |p|
            if p.categories.include?(params[:product][:categories][0])
              search_result << p
              @products = search_result
            else
              @products = []
            end
          end
        else
          if params[:product][:categories][2] == false || params[:product][:categories][2] == "---"
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][1])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          else
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][2])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          end
        end
      end
    else
      search_products = Product.where('title LIKE(?) OR text LIKE(?)', "%#{params[:keyword]}%","%#{params[:keyword]}%").order(created_at:"desc")

      search_result = []
      if params[:product][:categories][0] == false || params[:product][:categories][0] == "---"
        @products = search_products
      else
        if params[:product][:categories][1] == false || params[:product][:categories][1] == "---"
          search_products.each do |p|
            if p.categories.include?(params[:product][:categories][0])
              search_result << p
              @products = search_result
            else
              @products = []
            end
          end
        else
          if params[:product][:categories][2] == false || params[:product][:categories][2] == "---"
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][1])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          else
            search_products.each do |p|
              if p.categories.include?(params[:product][:categories][2])
                search_result << p
                @products = search_result
              else
                @products = []
              end
            end
          end
        end
      end
    end
    
    @category_parent_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    render search_products_path
  end


  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  def image_destroy
    @image = Image.find(params[:image_id])
    @image.destroy
  end

  private
  def product_params
    params.require(:product).permit(
      :title,
      :text,
      :price,
      :saler_id,
      {categories: []},
      images_attributes: [:id, :image],
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_like
    @like = Like.new
  end

  def load_mydata
    @image = Image.where(product_id: @product)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_box.html.haml
.product-box
  .product-box-conteiner
    .product-main-content
      .product-image
        .product-image__main
          - @image.each_with_index do |i, index|
            = image_tag(i.image.url, id: "product_image", class: "image-top imagemain#{index}")
        .product-image__sub
          - @image.each_with_index do |i, index|
            = image_tag(i.image.url, id: "product_image", class: "image-subtop imagesub#{index}")
      .product-detail
        %h1.product-name
          = @product.title
        .product-introduce
          .product-introduce__title
            【概要】
          = simple_format(@product.text)

        .price-bar  
          %span.price-bar__bold
            = "¥#{@product.price.to_s.gsub(/(\d)(?=\d{3}+$)/, '\\1,')} "
          %span.price-bar__tax (税込)
          -# %span.price-bar__shipping-fee
          -#   = @freight

          - if user_signed_in?
            - unless @product.buyer_id == current_user.id || @product.saler_id == current_user.id
              = link_to "購入画面に進む", purchase_path(@product.id) , class: 'status-bar__purchase'
            - if @product.buyer_id.blank?
              - if @product.saler_id == current_user.id
                .product-edit-box
                  = link_to edit_product_path, class: 'text-decoration-none font-color-white' do
                    .product-edit-box__edit-btn
                      商品を編集する
                  = link_to product_path, method: :delete , class: 'text-decoration-none font-color-white', "data-confirm" => "本当に削除しますか？?" do
                    .product-edit-box__edit-btn
                      この商品を削除する

            - else
              - if @product.buyer_id == current_user.id || @product.saler_id == current_user.id
                = link_to product_messages_path(@product.id), class: 'status-bar__message' do
                  メッセージを送る

          - else
            = link_to "購入画面に進む", new_user_session_path, class: 'status-bar__purchase'

    .product-main-content
      .product-detail
        .sideways
          .sideways__left-thick
            .sideways__left-thick__title 出品者
          .sideways__-right-thick
            .sideways__right-thick__content
              .add-height
                = link_to user_path(@product.saler.id), class: 'font-color-black' do
                  = @product.saler.nickname
        .sideways
          .sideways__left-thick
            .sideways__left-thick__title カテゴリー
          .sideways__-right-thick
            .sideways__right-thick__content 
              .sideways__right-thick__content--categories
                = @product.categories[0]
                >
                = @product.categories[1]
                >
                = @product.categories[2]
        .sideways
          .sideways__left-thick
            .sideways__left-thick__title いいね!人数
          .sideways__-right-thick
            .sideways__right-thick__content
              .add-height{id: "like-btn-#{@product.id}"}
                - if user_signed_in?
                  = render "likes/likes", product: @product
                - else
                  #{@product.likes.count}人がいいね!しました
                  = link_to new_user_session_path, class: "text-decoration-none font-color-black" do
                    = fa_icon "heart-o"


        

app/views/products/_product_form.html.haml
= form_for product do |f|
  .exhibit-wrapper
    .exhibit-wrapper__main
      .exhibit-wrapper__main__header
        %h3 商品の情報を入力
      .exhibit-wrapper__main__image
        %label
          出品画像
          %span 必須
          ※最大10枚までアップロードできます
        .exhibit-wrapper__main__image__cards{data:{exhibitid:0}}
          %label.exhibit-wrapper__main__image__drag-wrapper
            .exhibit-wrapper__main__image__drag
              %p クリックしてファイルをアップロード
            -# - product.images.each_with_index do |image, j|
            -#   =image_tag image.image.to_s, class: "item-edit__image item-edit__image-#{j}"
            = f.fields_for :images do |i|
              =i.file_field :image, readonly: false, class: "exhibit-wrapper__main__image__drag__form"
              -# =i.check_box :_destroy, disabled: true, class: "exhibit-wrapper__main__image__drag__check-box"
            .exhibit-wrapper__main__image__cards_anchor
        .error-append__image
      .exhibit-wrapper__main__item
        .exhibit-wrapper__main__item__name
          %label 
            商品のオススメポイント
            %span 必須
          =f.text_area :title, maxlength: 200, class: "exhibit-wrapper__main__item__name__field", placeholder: "商品のオススメポイント（必須200文字まで）"
          .error-append__title
        .exhibit-wrapper__main__item__content
          %label 
            商品の説明
            %span 必須
          =f.text_area :text, maxlength: 1000, rows:"6", class: "exhibit-wrapper__main__item__content__area" , placeholder: "商品の説明（必須1,000文字以内）。"
          .error-append__detail
      .category
        .form__right
          .form-group
            .form-group__top
              %label
                カテゴリー
                %span 必須
            .listing-product-detail__category
              .select-wrap
                = f.select :categories, @category_parent_array, {}, {:name => 'product[categories][]', id: 'parent_category', class: 'select-default'}
      .price
        .sub-head
        .form__right
          %ul.sell-price
            %li.form-group
              .form-group__top
                .form-group__top__left
                  =f.label '価格'
                  %span 必須
                .form-group__top__right
                  = f.number_field :price, placeholder: '例) 300', class: 'form-group__top__right__input',id: 'price_calc'
                  .price-discription
                    販売価格(300〜9,999,999)
            %li.calculation
              .calculation__left 販売手数料(10%)
              .calculation__right
            %li.result
              .result__left 販売利益
              .result__right -

      .bottom 
        .bottom__p

        = f.hidden_field :saler_id, value: current_user.id
        = f.submit :"出品する", class: "btn-red btn-default"
        = link_to 'もどる', :back, class: "btn-gray btn-default"

app/views/products/edit.html.haml
= render "shared/sub_header"
= render "product_form", product: @product

app/views/products/index.html.haml
= render 'shared/header'

.index-wrapper
  .index-wrapper__products-box
    - @products.each do |product|
      .product-card
        .product-card__product-image
          = link_to product_path(product.id), class: "" do
            = image_tag(product.images[0].image.url, class: "index-product-image")
        .product-card__info
          .product-card__info__price
            ¥#{product.price.to_s.gsub(/(\d)(?=\d{3}+$)/, '\\1,')}
          .product-card__info__like{id: "like-btn-#{product.id}"}
            - if user_signed_in?
              = render "likes/likes", product: product
            - else
              #{product.likes.count}人がいいね!しました
              = link_to new_user_session_path, class: "text-decoration-none font-color-black" do
                = fa_icon "heart-o"
        .product-card__container
          .product-card__container__product-title
            %span= product.title
          -# .product-card__container__product-description
          -#   = product.saler.nickname

app/views/products/new.html.haml
= render "shared/sub_header"
= render "product_form", product: @product

app/views/products/search.html.haml
= render "shared/sub_header"
.search-contents
  .search-contents__left-select-box
    = form_with url: detail_search_products_path , method: :get, local: true, class: "search-contents__left-select-box__form" do |f|
      .search-contents__left-select-box__form__detail-search
        .search-contents__left-select-box__form__detail-search__box
          .search-contents__left-select-box__form__detail-search__box__main-title
            詳細検索
          .search-contents__left-select-box__form__detail-search__box__middle-title
            キーワードを追加する
            = f.text_field :keyword, value: params[:keyword], class: "search-contents__left-select-box__form__detail-search__box__middle-title__input-box"
          .search-contents__left-select-box__form__detail-search__box__middle-title
            カテゴリーを選択する
            .search-contents__left-select-box__form__detail-search__box__middle-title__select-lists
              .listing-product-detail__category
                .select-wrap
                  = f.select :categories, @category_parent_array, {}, {:name => 'product[categories][]', id: 'parent_category', class: 'select-default'}
          .search-contents__left-select-box__form__detail-search__box__middle-title
            価格
            .search-contents__left-select-box__form__detail-search__box__middle-title__select-lists
            = f.text_field :price_min, placeholder: "¥ Min", class: "search-contents__left-select-box__form__detail-search__box__middle-title__input-helf-box"
            〜
            = f.text_field :price_max, placeholder: "¥ Max",class: "search-contents__left-select-box__form__detail-search__box__middle-title__input-helf-box"
          .search-contents__left-select-box__form__detail-search__box__search-btn
            -# .search-contents__left-select-box__form__detail-search__box__search-btn__clear
            -#   クリア
            = f.submit "検索" ,class: "search-contents__left-select-box__form__detail-search__box__search-btn__search"

  .search-contents__search-results
    .search-contents__search-results__title
      #{params[:keyword]}
      %span の検索結果
    .search-contents__search-results__count
      - if @products.count == 0
        %span 該当する商品が見つかりません。検索条件を変えて、再度お試しください。
      - else
        1 - #{@products.count}件表示
    .search-contents__search-results__search-items
      .search-contents__search-results__search-items__main-contents
        - @products.each do |product|
          .search-contents__search-results__search-items__main-contents__items
            .search-contents__search-results__search-items__main-contents__items__left
              = link_to product_path(product.id), class: "" do
                = image_tag(product.images[0].image.to_s, class: "search-contents__search-results__search-items__main-contents__items__left__image")
            .search-contents__search-results__search-items__main-contents__items__right
              .search-contents__search-results__search-items__main-contents__items__right__detail
                .search-contents__search-results__search-items__main-contents__items__right__detail__price
                  ¥#{product.price.to_s.gsub(/(\d)(?=\d{3}+$)/, '\\1,')}
                .search-contents__search-results__search-items__main-contents__items__right__detail__like{id: "like-btn-#{product.id}"}
                  - if user_signed_in?
                    = render "likes/likes", product: product
                  - else
                    #{product.likes.count}人がいいね!しました
                    = link_to new_user_session_path, class: "text-decoration-none font-color-black" do
                      = fa_icon "heart-o"
              .search-contents__search-results__search-items__main-contents__items__right__container
                .search-contents__search-results__search-items__main-contents__items__right__container__title
                  = product.title
.footer
= render 'shared/footer'

app/views/products/show.html.haml
.wrapper
  = render "shared/sub_header"
  .buyer-show-main
    = render "product_box"
    -# = render "message_box"
    -# - breadcrumb :buyer_show_product, @product
    -# .breadcrumbs-buyer
    -#   = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-buyer__list"
    = render 'shared/footer'